repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0  # Use the latest version available
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
