name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install

      - name: Set environment variables from GitHub Secrets
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> $GITHUB_ENV

      - name: Run linting with black
        run: |
          poetry run black --check .


      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files

      - name: Run tests
        run: |
          poetry run pytest --verbose
