# .github/workflows/test.yml
name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        env:
          FLASK_ENV: testing
        run: poetry run pytest --verbose
